{
 "title": "HTTP Status Service",
 "tags": [ "http" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) > 0"
    }
   ]
  },
  {
   "title": "Request success (2xx-3xx) rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[2-3].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Request client error (4xx) rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[4].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Request server error (5xx) rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[5].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg request latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Max request latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{application=~\"$application\", uri!~\".*(prometheus|health).*\"})"
    }
   ]
  },
  {
   "title": "Request rates by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application, method, uri) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "5xx error rates by applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[5].*\"}[$__rate_interval])) by (application) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application) > 0",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "5xx error rates by applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[5].*\"}[$__rate_interval])) by (application) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application) > 0",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "5xx error rates by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[5].*\"}[$__rate_interval])) by (application, method, uri) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application, method, uri) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "4xx error rates by applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[4].*\"}[$__rate_interval])) by (application) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application) > 0",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "4xx error rates by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[4].*\"}[$__rate_interval])) by (application, method, uri) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application, method, uri) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "4xx error rates by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[4].*\"}[$__rate_interval])) by (application, method, uri) / sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) by (application, method, uri) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Successful requests (2xx/3xx) by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[2-3].*\"}[$__rate_interval])) by (application, method, uri, status) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Client errors (4xx) by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[4].*\"}[$__rate_interval])) by (application, method, uri, status) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Server errors (5xx) by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\", status=~\"[5].*\"}[$__rate_interval])) by (application, method, uri, status) > 0",
     "legendFormat": "{{application}} - {{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Avg Request latency by applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application) (rate(http_server_requests_seconds_sum{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) / sum by (application) (rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Avg Request latency by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application, method, uri) (rate(http_server_requests_seconds_sum{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) / sum by (application, method, uri) (rate(http_server_requests_seconds_count{application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))",
     "legendFormat": "{{application}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Application percentile response times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Application request latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "P90 request latency by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le, application))",
     "legendFormat": "P90 - {{application}}"
    }
   ]
  },
  {
   "title": "P95 request latency by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le, application))",
     "legendFormat": "P95 - {{application}}"
    }
   ]
  },
  {
   "title": "P99 request latency by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\"}[$__rate_interval])) by (le, application))",
     "legendFormat": "P99 - {{application}}"
    }
   ]
  }
 ]
}