{
 "title": "HTTP Status Overview",
 "tags": [
  "http",
  "tv-monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,job)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{job=~\"$job\"},application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per sec",
   "type": "stat",
   "description": "HTTP requests per second",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval])), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rates by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval])) by (application, uri)",
     "legendFormat": "{{application}}/{{uri}}"
    }
   ]
  },
  {
   "title": "Avg latency",
   "type": "stat",
   "description": "Average HTTP request latency",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=~\"$job\", application=~\"$application\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 latency by endpoint",
   "type": "timeseries",
   "description": "P90 HTTP request latency by endpoint",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, uri)(rate(http_server_requests_seconds_bucket{job=~\"$job\", application=~\"$application\"}[$__rate_interval])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "5xx errors per sec",
   "type": "stat",
   "description": "HTTP 5xx errors per second",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", status=~\"5.*\"}[$__rate_interval])), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx errors by endpoint",
   "type": "timeseries",
   "description": "Server error rates by endpoint",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", status=~\"5.*\"}[$__rate_interval])) by (application, uri)",
     "legendFormat": "{{application}}/{{uri}}"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "stat",
   "description": "P95 HTTP request latency",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(http_server_requests_seconds_bucket{job=~\"$job\", application=~\"$application\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 latency by endpoint",
   "type": "timeseries",
   "description": "P95 HTTP request latency by endpoint",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri)(rate(http_server_requests_seconds_bucket{job=~\"$job\", application=~\"$application\"}[$__rate_interval])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "2-3xx success rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", status=~\"[2-3].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4xx error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", status=~\"[4].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", status=~\"[5].*\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Request rates by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application, method, uri)(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{uri}} - {{application}}"
    }
   ]
  },
  {
   "title": "Client errors by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application, method, uri, status)(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", uri!~\".*(prometheus|health).*\", outcome=\"CLIENT_ERROR\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{uri}} - {{status}} - {{application}}"
    }
   ]
  },
  {
   "title": "Server errors by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (application, method, uri, status)(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", uri!~\".*(prometheus|health).*\", outcome=\"SERVER_ERROR\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{uri}} - {{status}} - {{application}}"
    }
   ]
  },
  {
   "title": "Latency by endpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application, method, uri)(rate(http_server_requests_seconds_sum{job=~\"$job\", application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])) / sum by (application, method, uri)(rate(http_server_requests_seconds_count{job=~\"$job\", application=~\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}} - {{application}}"
    }
   ]
  }
 ]
}